package com.CrimsonGlory.dropbox.Database;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import org.springframework.web.multipart.MultipartFile;

@DynamoDBTable(tableName = "FileInfo")
public class FileInfo {
    private String id;
    private MultipartFile file;
    private MultipartFile metadata;
    private MultipartFile authtext;

    public FileInfo(MultipartFile file, MultipartFile metadata, MultipartFile authtext){
        this.file = file;
        this.metadata = metadata;
        this.authtext = authtext;
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId(){
        return id;
    }

    @DynamoDBAttribute
    public MultipartFile getFile(){
        return file;
    }

    @DynamoDBAttribute
    public MultipartFile getMetadata(){
        return metadata;
    }

    @DynamoDBAttribute
    public MultipartFile getAuthtext(){
        return authtext;
    }

}
